version: '3.9'

services:
  # # loggin service started
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - logging-network
  
  fluent-bit:
    image: fluent/fluent-bit:4.2.2
    container_name: fluent-bit
    networks:
      - logging-network
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command:
      - /fluent-bit/bin/fluent-bit
      - -i
      - tail
      - -p
      - path=/var/lib/docker/containers/*/*.log
      - -p
      - read_from_head=true
      - -p
      - tag=docker.*
      - -o
      - loki
      - -p
      - host=loki
      - -p
      - port=3100
      - -p
      - labels=job=docker
      - -p
      - auto_kubernetes_labels=false

  grafana:
    image: grafana/grafana:10.3.0
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - logging-network

  # #loggin service ends 

  mongo:
    container_name: mongo_db
    image: mongo:6.0
    environment:
      MONGO_INITDB_DATABASE: mydb
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_user
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password
    command: ["--auth"]
    volumes:
      - mongo-data:/data/db
      - ./mongo_user.txt:/run/secrets/mongo_user:ro
      - ./mongo_password.txt:/run/secrets/mongo_password:ro
      - ./mongo-backup:/backup
    networks:
      - app-network
      - logging-network

  backend:
    container_name: node_backend_app
    image: anilnagarro24/advanced-backend-app:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./logs:/app/logs
      - ./mongo_user.txt:/run/secrets/mongo_user:ro
      - ./mongo_password.txt:/run/secrets/mongo_password:ro
    depends_on:
      - mongo
    networks:
      - app-network
      - logging-network
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

  frontend:
    container_name: frontend_app
    image: anilnagarro24/advanced-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network
      - logging-network

volumes:
  mongo-data:
  grafana-data:

networks:
  app-network:
    driver: bridge
  logging-network:
    driver: bridge
